export enum AuditEventType {
  ROLE_ASSIGNED = "ROLE_ASSIGNED",
  ROLE_CHANGED = "ROLE_CHANGED",
  ROLE_REMOVED = "ROLE_REMOVED",

  USER_SUSPENDED = "USER_SUSPENDED",
  USER_REACTIVATED = "USER_REACTIVATED",

  PERMISSION_GRANTED = "PERMISSION_GRANTED",
  PERMISSION_REVOKED = "PERMISSION_REVOKED",
}